#!/usr/bin/env bash
# ──────────────────────────────────────────────
#   install.sh — set up the dotfiles on a fresh Arch + Hyprland install.
#
#   What it does:
#     1. Backs up any existing config dirs that would be replaced.
#     2. Symlinks every app config from <repo>/config/ into ~/.config/.
#     3. Symlinks shell files (zshrc, bashrc, ...) into $HOME.
#     4. Sets up the active-theme symlink chain (defaults to "Noro").
#     5. Copies the optimized wallpaper collections into
#        ~/.local/share/wallpapers (the XDG data location all scripts use).
#     6. Regenerates the matugen color palette from the current wallpaper.
#
#   Safe to re-run: existing symlinks are refreshed, backups are only
#   taken for real (non-symlink) files that are about to be replaced.
# ──────────────────────────────────────────────

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BACKUP_DIR="$HOME/.config-backup-$(date +%Y%m%d-%H%M%S)"
ACTIVE_THEME="${ACTIVE_THEME:-Noro}"
THEME_LOWER="$(printf '%s' "$ACTIVE_THEME" | tr '[:upper:]' '[:lower:]')"

info()  { printf '  \033[1;32m==>\033[0m %s\n' "$*"; }
warn()  { printf '  \033[1;33m ->\033[0m %s\n' "$*"; }

# ── 1. App configs → ~/.config ────────────────
link_config() {
    local name="$1"
    local src="$REPO_ROOT/config/$name"
    local dst="$HOME/.config/$name"

    [ -d "$src" ] || { warn "skip $name (not in repo)"; return; }
    mkdir -p "$HOME/.config"

    if [ -L "$dst" ]; then
        rm "$dst"                                   # refresh existing symlink
    elif [ -e "$dst" ]; then
        mkdir -p "$BACKUP_DIR"
        mv "$dst" "$BACKUP_DIR/$name"
        warn "backed up existing $name -> $BACKUP_DIR/$name"
    fi
    ln -s "$src" "$dst"
    info "linked $name"
}

# App dirs versioned in this repo.
APPS=(
    hypr
    waybar
    rofi
    kitty
    btop
    swayosd
    matugen
    nvim
    zed
    gtk-3.0
    gtk-4.0
)

# Apps whose only config is generated by matugen at runtime — just make sure
# the dir exists so the templates have somewhere to write.
GENERATED_APPS=(
    dunst
    fastfetch
    ghostty
    helium-theme
)

echo "==> Linking app configs into ~/.config"
for app in "${APPS[@]}"; do
    link_config "$app"
done

# Generated-only apps: ensure their ~/.config dirs exist (matugen writes here).
for app in "${GENERATED_APPS[@]}"; do
    mkdir -p "$HOME/.config/$app"
    info "prepared $app (config generated by matugen)"
done

# ── 2. Shell files → $HOME ───────────────────
link_home() {
    local name="$1"                 # name inside repo shell/
    local dotname=".$1"             # name in $HOME, case-adjusted below
    local src="$REPO_ROOT/shell/$name"
    local dst="$HOME/$dotname"

    [ -f "$src" ] || { warn "skip $name (not in repo)"; return; }

    if [ -L "$dst" ]; then
        rm "$dst"
    elif [ -e "$dst" ]; then
        mkdir -p "$BACKUP_DIR"
        mv "$dst" "$BACKUP_DIR/$dotname"
        warn "backed up existing $dotname -> $BACKUP_DIR/$dotname"
    fi
    ln -s "$src" "$dst"
    info "linked $dotname"
}

echo
echo "==> Linking shell files into \$HOME"
link_home zshrc
link_home bashrc
link_home bash_profile
link_home dircolors
link_home gitconfig

# ── 3. Active theme symlink chain ────────────
echo
echo "==> Setting active theme: $ACTIVE_THEME"
HYPR_CFG="$HOME/.config/hypr"
WAYBAR_CFG="$HOME/.config/waybar"
ROFI_CFG="$HOME/.config/rofi"

if [ -f "$HYPR_CFG/themes/$THEME_LOWER/theme.conf" ]; then
    ln -sf "$HYPR_CFG/themes/$THEME_LOWER/theme.conf" "$HYPR_CFG/theme.conf"
    ln -sf "$HYPR_CFG/themes/$THEME_LOWER/theme.lua"  "$HYPR_CFG/theme.lua"
    ln -sf "$WAYBAR_CFG/themes/$THEME_LOWER/config.jsonc" "$WAYBAR_CFG/config.jsonc"
    ln -sf "$WAYBAR_CFG/themes/$THEME_LOWER/style.css"    "$WAYBAR_CFG/style.css"
    ln -sf "$ROFI_CFG/themes/$THEME_LOWER/launcher.rasi"  "$ROFI_CFG/active-launcher.rasi"
    ln -sf "$ROFI_CFG/themes/$THEME_LOWER/scripts.rasi"   "$ROFI_CFG/active-scripts.rasi"
    ln -sf "$ROFI_CFG/themes/$THEME_LOWER/picker.rasi"    "$ROFI_CFG/active-picker.rasi"
    printf '%s\n' "$ACTIVE_THEME" > "$HYPR_CFG/.active-theme"
    info "theme chain linked ($THEME_LOWER)"
else
    warn "theme '$ACTIVE_THEME' not found, leaving existing chain"
fi

# ── 4. Wallpapers → ~/.local/share/wallpapers ─
echo
echo "==> Installing wallpaper collections"
WALL_DST="$HOME/.local/share/wallpapers"
mkdir -p "$WALL_DST"
for theme_dir in "$REPO_ROOT/wallpapers"/*/; do
    name="$(basename "$theme_dir")"
    mkdir -p "$WALL_DST/$name"
    cp -p "$theme_dir"* "$WALL_DST/$name/" 2>/dev/null || true
    info "wallpapers: $name ($(ls "$WALL_DST/$name" | wc -l) files)"
done

# ── 5. Executable bits ───────────────────────
echo
echo "==> Ensuring helper scripts are executable"
find "$REPO_ROOT/config/hypr/scripts"  -type f -exec chmod +x {} \; 2>/dev/null || true
find "$REPO_ROOT/config/waybar/scripts" -type f -exec chmod +x {} \; 2>/dev/null || true
find "$REPO_ROOT/config/rofi/scripts"  -type f -exec chmod +x {} \; 2>/dev/null || true
info "scripts marked executable"

# ── 5b. User helper scripts → ~/.local/bin ──
echo
echo "==> Installing user helper scripts into ~/.local/bin"
mkdir -p "$HOME/.local/bin"
for helper in "$REPO_ROOT/bin"/*; do
    [ -f "$helper" ] || continue
    cp -p "$helper" "$HOME/.local/bin/$(basename "$helper")"
    chmod +x "$HOME/.local/bin/$(basename "$helper")"
    info "helper: $(basename "$helper")"
done

# ── 5c. Rofi image-carousel theme ────────────
echo
echo "==> Installing rofi image-carousel theme"
ROFI_SRC="$REPO_ROOT/config/rofi/themes/active-image-carousel.rasi"
ROFI_DST="$HOME/.config/rofi/themes/active-image-carousel.rasi"
mkdir -p "$HOME/.config/rofi/themes"
if [ -f "$ROFI_SRC" ]; then
    # rofi is symlinked to the repo, so the source may already BE the target —
    # cp would fail with "same file" and abort the whole install under set -e.
    if [ "$ROFI_SRC" -ef "$ROFI_DST" ]; then
        info "rofi image-carousel theme already in place (repo is symlinked)"
    else
        cp -p "$ROFI_SRC" "$ROFI_DST"
        info "rofi image-carousel theme installed"
    fi
else
    warn "rofi image-carousel theme not found in repo"
fi

# ── 6. Initial palette ───────────────────────
echo
echo "==> Generating initial color palette"
if command -v matugen >/dev/null 2>&1; then
    WALL="$(find "$WALL_DST/$THEME_LOWER" -type f \( -iname '*.jpg' -o -iname '*.jpeg' -o -iname '*.png' \) 2>/dev/null | sort | head -n 1)"
    if [ -n "$WALL" ]; then
        matugen image "$WALL" -c "$HOME/.config/matugen/config.toml" --source-color-index 0 \
            && info "palette generated from $WALL" \
            || warn "matugen failed, run it manually after first login"
    else
        warn "no wallpaper found for theme '$THEME_LOWER'"
    fi
    else
        warn "matugen not installed; palette will be generated on first theme switch"
    fi

    # ── 7. Default image viewer ──────────────
    echo
    echo "==> Setting default image viewer (eog)"
    sudo pacman -S --noconfirm eog >/dev/null 2>&1 || warn "eog install skipped"
    if [ -f "$HOME/.config/mimeapps.list" ]; then
        sed -i 's#=eog\.desktop#=org.gnome.eog.desktop#g' "$HOME/.config/mimeapps.list"
        for m in image/jpeg image/png image/gif image/webp image/bmp image/x-ms-bmp image/tiff; do
            xdg-mime default org.gnome.eog.desktop "$m" 2>/dev/null || true
        done
        info "image MIME types set to org.gnome.eog.desktop"
    else
        warn "~/.config/mimeapps.list not found; image MIME defaults unchanged"
    fi

    echo
    echo "Done. Log out and select Hyprland at the greeter (or start it) to use the new setup."
if [ -d "$BACKUP_DIR" ]; then
    echo "Backups of replaced files are in: $BACKUP_DIR"
fi
exit 0
