-- ─────────────────────────────────────────────
--   Hyprland Colors — Lua (generated by Matugen)
--   Mirrors colors.conf · do not edit manually
--   Source template: matugen/templates/hyprland.lua
-- ─────────────────────────────────────────────
active_border = "{{colors.primary.default.hex_stripped}}"
inactive_border = "{{colors.surface_variant.default.hex_stripped}}"
background = "{{colors.surface.default.hex_stripped}}"

return {
    active_border = active_border,
    inactive_border = inactive_border,
    background = background,
}
