-- ──────────────────────────────────────────────
--   Hyprland Configuration — Lua (0.55+)
--   System: Intel Core i5-13500H · Iris Xe · 16 GB RAM
--   Modular: this file only stitches together the modules below.
--   See wiki.hypr.land + /usr/share/hypr/stubs/hl.meta.lua for API details.
--
--   Modules (each require is an isolated scope; errors in one do not stop others):
--     vars          Shared command strings / variables (returned table)
--     env           Monitors + environment variables
--     colors        Color palette (generated by Matugen)
--     theme         Active theme (symlink into hypr/themes/*/)
--     input         Keyboard / mouse / touchpad
--     autostart     Startup applications
--     look          Animations, curves, layouts, misc / render / debug
--     binds         Keybindings
--     window-rules  Window rules
-- ──────────────────────────────────────────────

pcall(require, "vars")
pcall(require, "env")
pcall(require, "colors")
pcall(require, "theme")
pcall(require, "input")
pcall(require, "autostart")
pcall(require, "look")
pcall(require, "binds")
pcall(require, "window-rules")
