# ── Glass Theme Config ──
source = ~/.config/hypr/colors.conf

decoration {
    rounding = 20
    blur {
        enabled = true
    }
    shadow {
        enabled = false
        range = 10
        render_power = 2
        color = rgba(00000030)
    }
}
general {
    gaps_in = 8
    gaps_out = 16
    border_size = 1
    col.active_border = rgb($active_border)
    col.inactive_border = rgb($inactive_border)
    layout = dwindle
    allow_tearing = false
}
