-- Matugen dynamic theme (restored from pre-LazyVim config)
-- Applies the colors generated by matugen (lua/matugen-colors.lua) on top of
-- the colorscheme, and reloads them when matugen regenerates (SIGUSR1).

local M = {}

function M.apply()
  local ok, colors = pcall(require, "matugen-colors")
  if not ok then
    return
  end

  local c = colors.colors
  local hi = vim.api.nvim_set_hl

  hi(0, "Normal", { fg = c.fg, bg = c.bg })
  hi(0, "NormalFloat", { fg = c.fg, bg = c.surface })
  hi(0, "CursorLine", { bg = c.surface })
  hi(0, "Visual", { bg = c.primary, fg = c.on_primary })
  hi(0, "Search", { bg = c.tertiary, fg = c.bg })
  hi(0, "IncSearch", { bg = c.primary, fg = c.on_primary })

  hi(0, "LineNr", { fg = c.outline })
  hi(0, "CursorLineNr", { fg = c.primary, bold = true })

  hi(0, "StatusLine", { fg = c.fg, bg = c.surface })
  hi(0, "StatusLineNC", { fg = c.outline, bg = c.bg })

  hi(0, "Pmenu", { fg = c.fg, bg = c.surface })
  hi(0, "PmenuSel", { fg = c.on_primary, bg = c.primary })
  hi(0, "PmenuThumb", { bg = c.primary })

  hi(0, "Comment", { fg = c.outline, italic = true })
  hi(0, "Constant", { fg = c.tertiary })
  hi(0, "String", { fg = c.secondary })
  hi(0, "Identifier", { fg = c.fg })
  hi(0, "Function", { fg = c.primary })
  hi(0, "Statement", { fg = c.primary, bold = true })
  hi(0, "Keyword", { fg = c.primary })
  hi(0, "Type", { fg = c.tertiary })
  hi(0, "Special", { fg = c.secondary })
  hi(0, "Error", { fg = c.error })
  hi(0, "Todo", { fg = c.on_primary, bg = c.primary, bold = true })

  hi(0, "DiagnosticError", { fg = c.error })
  hi(0, "DiagnosticWarn", { fg = c.tertiary })
  hi(0, "DiagnosticInfo", { fg = c.primary })
  hi(0, "DiagnosticHint", { fg = c.secondary })

  hi(0, "DiffAdd", { bg = c.primary, fg = c.on_primary })
  hi(0, "DiffChange", { bg = c.secondary, fg = c.on_secondary })
  hi(0, "DiffDelete", { bg = c.error, fg = c.bg })
end

M.apply()

local group = vim.api.nvim_create_augroup("user_matugen", { clear = true })

vim.api.nvim_create_autocmd("ColorScheme", {
  group = group,
  callback = M.apply,
})

vim.api.nvim_create_autocmd("Signal", {
  group = group,
  pattern = "SIGUSR1",
  callback = function()
    package.loaded["matugen-colors"] = nil
    M.apply()
  end,
})

return M