[config]
# Generate colors in dark mode by default
default_mode = "dark"

[templates.waybar]
input_path = "~/.config/matugen/templates/waybar.css"
output_path = "~/.config/waybar/colors.css"

[templates.kitty]
input_path = "~/.config/matugen/templates/kitty.conf"
output_path = "~/.config/kitty/colors.conf"

[templates.rofi]
input_path = "~/.config/matugen/templates/rofi.rasi"
output_path = "~/.config/rofi/colors.rasi"

[templates.hyprland]
input_path = "~/.config/matugen/templates/hyprland.conf"
output_path = "~/.config/hypr/colors.conf"

[templates.hyprland_lua]
input_path = "~/.config/matugen/templates/hyprland.lua"
output_path = "~/.config/hypr/colors.lua"

[templates.pywalfox]
input_path = "~/.config/matugen/templates/pywalfox.json"
output_path = "~/.cache/wal/colors.json"

[templates.antigravity]
input_path = "~/.config/matugen/templates/antigravity.json"
output_path = "~/.config/Antigravity/User/settings.json"

[templates.brave]
input_path = "~/.config/matugen/templates/brave.css"
output_path = "~/.config/brave/colors.css"

[templates.dolphin]
input_path = "~/.config/matugen/templates/dolphin.colors"
output_path = "~/.local/share/color-schemes/Matugen.colors"

[templates.nvim]
input_path = "~/.config/matugen/templates/nvim.lua"
output_path = "~/.config/nvim/lua/matugen-colors.lua"

[templates.gtk3]
input_path = "~/.config/matugen/templates/gtk3.css"
output_path = "~/.config/gtk-3.0/gtk.css"

[templates.gtk4]
input_path = "~/.config/matugen/templates/gtk4.css"
output_path = "~/.config/gtk-4.0/gtk.css"

[templates.gtk4_dark]
input_path = "~/.config/matugen/templates/gtk4.css"
output_path = "~/.config/gtk-4.0/gtk-dark.css"

[templates.sourceview]
input_path = "~/.config/matugen/templates/sourceview.xml"
output_path = "~/.local/share/gtksourceview-5/styles/Matugen.xml"

[templates.swayosd]
input_path = "~/.config/matugen/templates/swayosd.css"
output_path = "~/.config/swayosd/style.css"

[templates.helium_theme]
input_path = "~/.config/matugen/templates/helium-theme.json"
output_path = "~/.config/helium-theme/manifest.json"

[templates.vscode]
input_path = "~/.config/matugen/templates/vscode-colors.json"
output_path = "~/.config/Code/User/matugen-colors.json"

[templates.zed]
input_path = "~/.config/matugen/templates/zed.json"
output_path = "~/.config/zed/themes/matugen.json"

[templates.ghostty]
input_path = "~/.config/matugen/templates/ghostty.conf"
output_path = "~/.config/ghostty/config.ghostty"

[templates.btop]
input_path = "~/.config/matugen/templates/btop.theme"
output_path = "~/.config/btop/themes/matugen.theme"

[templates.fastfetch]
input_path = "~/.config/matugen/templates/fastfetch.jsonc"
output_path = "~/.config/fastfetch/config.jsonc"

[templates.hyprlock]
input_path = "~/.config/matugen/templates/hyprlock.conf"
output_path = "~/.config/hypr/hyprlock-colors.conf"

[templates.swaync]
input_path = "~/.config/matugen/templates/swaync.css"
output_path = "~/.config/swaync/style.css"
